spring:
  security:
    oauth2:
      client:
        registration:
          gitee:
            client-id: 71d5c8b12c44ed568480413da7fe5403606666caa4c4807dcd7c8dd02bf676a1
            client-secret: 876ae45f43efe1ad7ba6ed5b2e677ef7834c1986d21a2a5b65a969108a2ac48c
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            client-name: Gitee
          github:
            client-id: b4713d47174917b34c28
            client-secret: 898389369c2e9f3d1d0ff4543ba1d9b45adfd093
        provider:
          gitee:
            authorization-uri: https://gitee.com/oauth/authorize
            token-uri: https://gitee.com/oauth/token
            user-info-uri: https://gitee.com/api/v5/user
            user-name-attribute: name